language: php

matrix:
  include:
    - php: 5.2
      dist: precise
    - php: 5.3
      dist: precise
    - php: 5.6
      dist: trusty
    - php: 7.0
      dist: trusty
    - php: 7.1
      dist: trusty

before_script: composer install

script: ./vendor/bin/phing

after_script: ./vendor/bin/coveralls -v
